name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        echo OK
        # sudo apt install cython
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install testtools doctools configobj flake8 cython docutils
        pip install -U pip setuptools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build bazaar
      run: |
        make 
    - name: Build documents
      run: | 
        echo OK
        # make docs

    - name: Run Tests
      run: | 
        make check

